In [26]:
import numpy as np

text = ['I like apples',
'You love dogs',
'play soccer',
'She reads books',
'He drinks water',
'eat pizza',
'Birds fly high',
'Cats chase mice']

In [27]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [28]:
tokenizer.fit_on_texts(text)

In [29]:
sequence = tokenizer.texts_to_sequences(text)

In [30]:
sequence

[[1, 2, 3],
 [4, 5, 6],
 [7, 8],
 [9, 10, 11],
 [12, 13, 14],
 [15, 16],
 [17, 18, 19],
 [20, 21, 22]]

In [31]:
from keras.utils import pad_sequences
sequence = pad_sequences(sequence,padding='post')

In [32]:
word_count = len(tokenizer.word_index)
print(word_count)

22


In [56]:
from keras.models import Sequential
from keras.layers import Input, Embedding
model = Sequential()
model.add(Embedding(input_dim=1000, output_dim=2, input_shape=(3,)))
print(model.summary)
model.summary()

<bound method Model.summary of <Sequential name=sequential_17, built=True>>


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_17"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_12 (Embedding)        │ (None, 3, 2)           │         2,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,000 (7.81 KB)

 Trainable params: 2,000 (7.81 KB)

 Non-trainable params: 0 (0.00 B)

In [53]:
 model.compile('adam','accuracy')

In [54]:
prediction =model.predict(sequence)
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
[[[-0.00259013 -0.04112296]
  [-0.04422103 -0.02955644]
  [ 0.04452823  0.02681298]]

 [[-0.02632741  0.01526643]
  [-0.02212705 -0.0112699 ]
  [-0.02379818 -0.00762168]]

 [[-0.02448443 -0.00587931]
  [-0.02174759 -0.04171783]
  [ 0.0327772   0.02803384]]

 [[ 0.04216427  0.02643913]
  [ 0.03470865 -0.01420178]
  [ 0.03183167  0.0475476 ]]

 [[-0.03680714  0.03167165]
  [ 0.02699507 -0.03422433]
  [-0.01129381  0.02178306]]

 [[-0.04159536  0.02394781]
  [ 0.04998494 -0.01642469]
  [ 0.0327772   0.02803384]]

 [[-0.01651573  0.0412222 ]
  [-0.04440897 -0.00639573]
  [ 0.01847782 -0.03733845]]

 [[-0.03626756  0.01918269]
  [ 0.02728618 -0.01179072]
  [ 0.01096821 -0.04145124]]]
